CREATE SEQUENCE SEQ_FP_DOC_AUTH_MASTER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FP_DOC_AUTH_TEMP START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FP_DOC_AUTH_AUD START WITH 1 INCREMENT BY 1;

CREATE TABLE T_FP_DOC_AUTH_MASTER (
    ID NUMBER PRIMARY KEY,
    FP_DOC_ID NUMBER UNIQUE,
    FACILITY_PAPER_ID NUMBER,
    ADDED_BY VARCHAR2(100),
    ADDED_DATE TIMESTAMP,
    ADDED_USER_DISPLAY_NAME VARCHAR2(255),
    ADDED_USER_WORK_CLASS VARCHAR2(100),
    ADDED_USER_DIV_CODE VARCHAR2(50),
    ADDED_USER_BRANCH_CODE VARCHAR2(50),
    CURRENT_ASSIGN_USER VARCHAR2(100),
    VERIFIED_BY VARCHAR2(100),
    VERIFIED_DATE TIMESTAMP,
    VERIFIED_USER_DISPLAY_NAME VARCHAR2(255),
    VERIFIED_USER_WORK_CLASS VARCHAR2(100),
    VERIFIED_USER_DIV_CODE VARCHAR2(50),
    VERIFIED_USER_BRANCH_CODE VARCHAR2(50),
    AUTHORIZED_BY VARCHAR2(100),
    AUTHORIZED_DATE TIMESTAMP,
    AUTHORIZED_USER_DISPLAY_NAME VARCHAR2(255),
    AUTHORIZED_USER_WORK_CLASS VARCHAR2(100),
    AUTHORIZED_USER_DIV_CODE VARCHAR2(50),
    AUTHORIZED_USER_BRANCH_CODE VARCHAR2(50),
    IS_ADDED VARCHAR2(1),
    IS_VERIFIED VARCHAR2(1),
    IS_AUTHORIZED VARCHAR2(1)
);

CREATE TABLE T_FP_DOC_AUTH_TEMP (
    ID NUMBER PRIMARY KEY,
    FP_DOC_ID NUMBER UNIQUE,
    FACILITY_PAPER_ID NUMBER,
    ADDED_BY VARCHAR2(100),
    ADDED_DATE TIMESTAMP,
    ADDED_USER_DISPLAY_NAME VARCHAR2(255),
    ADDED_USER_WORK_CLASS VARCHAR2(100),
    ADDED_USER_DIV_CODE VARCHAR2(50),
    ADDED_USER_BRANCH_CODE VARCHAR2(50),
    CURRENT_ASSIGN_USER VARCHAR2(100),
    VERIFIED_BY VARCHAR2(100),
    VERIFIED_DATE TIMESTAMP,
    VERIFIED_USER_DISPLAY_NAME VARCHAR2(255),
    VERIFIED_USER_WORK_CLASS VARCHAR2(100),
    VERIFIED_USER_DIV_CODE VARCHAR2(50),
    VERIFIED_USER_BRANCH_CODE VARCHAR2(50),
    AUTHORIZED_BY VARCHAR2(100),
    AUTHORIZED_DATE TIMESTAMP,
    AUTHORIZED_USER_DISPLAY_NAME VARCHAR2(255),
    AUTHORIZED_USER_WORK_CLASS VARCHAR2(100),
    AUTHORIZED_USER_DIV_CODE VARCHAR2(50),
    AUTHORIZED_USER_BRANCH_CODE VARCHAR2(50),
    IS_ADDED VARCHAR2(1),
    IS_VERIFIED VARCHAR2(1),
    IS_AUTHORIZED VARCHAR2(1)
);

CREATE TABLE T_FP_DOC_AUTH_AUD (
    AUD_ID NUMBER PRIMARY KEY,
    ID NUMBER,
    FP_DOC_ID NUMBER,
    FACILITY_PAPER_ID NUMBER,
    ADDED_BY VARCHAR2(100),
    ADDED_DATE TIMESTAMP,
    ADDED_USER_DISPLAY_NAME VARCHAR2(255),
    ADDED_USER_WORK_CLASS VARCHAR2(100),
    ADDED_USER_DIV_CODE VARCHAR2(50),
    ADDED_USER_BRANCH_CODE VARCHAR2(50),
    CURRENT_ASSIGN_USER VARCHAR2(100),
    VERIFIED_BY VARCHAR2(100),
    VERIFIED_DATE TIMESTAMP,
    VERIFIED_USER_DISPLAY_NAME VARCHAR2(255),
    VERIFIED_USER_WORK_CLASS VARCHAR2(100),
    VERIFIED_USER_DIV_CODE VARCHAR2(50),
    VERIFIED_USER_BRANCH_CODE VARCHAR2(50),
    AUTHORIZED_BY VARCHAR2(100),
    AUTHORIZED_DATE TIMESTAMP,
    AUTHORIZED_USER_DISPLAY_NAME VARCHAR2(255),
    AUTHORIZED_USER_WORK_CLASS VARCHAR2(100),
    AUTHORIZED_USER_DIV_CODE VARCHAR2(50),
    AUTHORIZED_USER_BRANCH_CODE VARCHAR2(50),
    IS_ADDED VARCHAR2(1),
    IS_VERIFIED VARCHAR2(1),
    IS_AUTHORIZED VARCHAR2(1),
    AUD_DATE TIMESTAMP,
    AUD_ACTION VARCHAR2(50)
);

-- Optional: enforce FP document link for temp rows (run after T_FP_DOCUMENT exists)
-- ALTER TABLE T_FP_DOC_AUTH_TEMP ADD CONSTRAINT FK_FP_DOC_AUTH_TEMP_FP_DOC
--   FOREIGN KEY (FP_DOC_ID) REFERENCES T_FP_DOCUMENT (FP_DOCUMENT_ID);
