# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:oracle:thin:@dc2tst-scan.sampath.lk:1523/tcmndb?oracle.jdbc.timezoneAsRegion=false
spring.datasource.username=casv2apn
spring.datasource.password=ENC(egnazb8h9Lolhm67zoKJe0jwnQmolc6U)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


springdoc.swagger-ui.path=/swagger-ui.html

app.allow.sending.email=true

#Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=2000000


# Encryption Data
enc.key=kFOeHvpni5XmL2SO5qHl+Sn9tvKPdFoTrex0e06qCwvMXBmehbRbIw4p8fXU0ClBknsJ/WBaWnF66nHMsEo8I/9EUTon/LwpU34eAz4IH/rs1/MY6L4Bvo50bVx2HIIzejlxui7rw8t/cq2Bb3qGO83m5upcbzyRlwMhTFxhNkJ35SzzpZ4/caegLTfVJbzO5xYjN07ChIfkAKHR2YQWmDwosXVj4hAjdpVYKrOG0d4CElJLoKTRiBttMBgt7PpkO2h9H+QKRJAhklGEltOdWO176sY/q/g27A3o8r2+YTuIGxHQ06vHt7kY6m3UQc6+Ghdl5ja3sYHULez7nq3M/w==
cert.path=C:/usr/SampathBank.p12
cert.password=password

logging.path=logs/
logging.common-name=cas_storage_LOG
logging.error-name=cas_storage_ERROR_LOG

apps.integration.create.das.case.enable=true
apps.integration.create.das.case.url=http://192.125.125.179:9003/SDASAPI/sdascase/

apps.integration.create.das.document.ref.enable=true
apps.integration.create.das.document.ref.url=http://192.125.125.179:9003/SDASAPI/Document/

apps.integration.get.das.documents.by.caseId.ref.enable=true
apps.integration.get.das.documents.by.caseId.url=http://192.125.125.179:9003/SDASAPI/casedocuments/{caseId}/

apps.integration.get.das.document.by.docId.enable=true
apps.integration.get.das.document.by.docId.url=http://192.125.125.179:9003/SDASAPI/viewdocument/{documentId}/{caseId}/

das.log.originalBase64.enabled=false
apps.print.html.template.path=json/

apps.documentService.case.LastNodeID=449
apps.documentService.case.LastNodeElementOrder=1

apps.documentService.document.Foldersavein=SDAS
apps.documentService.document.Objectstorename=SDASTOS
apps.documentService.document.Appreqid=1234
apps.documentService.document.Sdasdocuemntsecurity=26
apps.documentService.document.Sdasdocumenttypeid=1
