ALTER TABLE T_FP_DOCUMENT
ADD (
    CASE_ID varchar2(200),
    DOCUMENT_REFERENCE varchar2(200)
);

ALTER TABLE T_FP_DOCUMENT
ADD DOCUMENT_STORAGE_ID NUMBER(10);

CREATE INDEX IDX_T_FP_DOCUMENT_CASE_ID ON T_FP_DOCUMENT (CASE_ID);

ALTER TABLE T_FP_DOCUMENT
ADD DOC_STATUS VARCHAR2(10);

-- Backfill: treat all existing FP documents as PRE until explicitly set otherwise
UPDATE T_FP_DOCUMENT
SET DOC_STATUS = 'PRE'
WHERE DOC_STATUS IS NULL;